phase='train'
#phase='test'
dataset_path='/mnt/lustre/wanghao3/projects/PatCore/Dataset'
#train_list='/mnt/lustre/wanghao3/projects/PatCore/PatchCore_anomaly_detection/datapath/40_jier/train/train.lst'
#train_list='/mnt/lustre/wanghao3/projects/PatCore/PatchCore_anomaly_detection/datapath/hongzao/train/train_2.lst'
#train_list='/mnt/lustre/wanghao3/projects/PatCore/PatchCore_anomaly_detection/datapath/0908-0924/Cu_0/train_1000.lst'
#train_list='/mnt/lustre/wanghao3/projects/PatCore/PatchCore_anomaly_detection/datapath/0908-0924/Al_1/train_2000.lst'
#train_list='/mnt/lustre/wanghao3/projects/Knowlege_distillation_AD/Dataset/ciwa_data_list/3/train_1000.lst'
#train_list='/mnt/lustre/wanghao3/projects/PatCore/PatchCore_anomaly_detection/datapath/0908-0924/Al_3/train_2000.lst'
train_list='/mnt/lustre/wanghao3/projects/PatCore/PatchCore_anomaly_detection/datapath/0908-0924/train/train.lst'
#train_list='/mnt/lustre/wanghao3/projects/PatCore/PatchCore_anomaly_detection/datapath/0908-0924/Cu_2/train_2000.lst'
#train_list='/mnt/lustre/wanghao3/projects/PatCore/PatchCore_anomaly_detection/Dataset/1011/train/train_v0.1.lst'
#train_list='/mnt/lustre/wanghao3/projects/PatCore/PatchCore_anomaly_detection/Dataset/train_500/train_list.lst'
#train_list='/mnt/lustre/wanghao3/projects/PatCore/PatchCore_anomaly_detection/Dataset/train_sample490/train/train_ds_490.lst'
#train_list='/mnt/lustre/wanghao3/projects/PatCore/PatchCore_anomaly_detection/Dataset/train_sample_2000/train/train.lst'
#train_list='/mnt/lustre/wanghao3/projects/PatCore/PatchCore_anomaly_detection/Dataset/1011/train/train_v0.0.lst'
#test_list='/mnt/lustre/wanghao3/projects/PatCore/PatchCore_anomaly_detection/Dataset/train_500/test_list.lst'
#test_list='/mnt/lustre/wanghao3/projects/PatCore/PatchCore_anomaly_detection/Dataset/train_sample490/test/test_100_170.lst'
#test_list='/mnt/lustre/wanghao3/projects/PatCore/PatchCore_anomaly_detection/Dataset/1011/test/test_v0.0.lst'
#test_list='/mnt/lustre/wanghao3/projects/PatCore/PatchCore_anomaly_detection/datapath/0908-0924/Cu_0/test.lst'
#test_list='/mnt/lustre/wanghao3/projects/PatCore/PatchCore_anomaly_detection/datapath/0908-0924/Cu_2/test.lst'
#test_list='/mnt/lustre/wanghao3/projects/PatCore/PatchCore_anomaly_detection/datapath/0908-0924/Al_1/test.lst'
#test_list='/mnt/lustre/wanghao3/projects/PatCore/PatchCore_anomaly_detection/datapath/0908-0924/Al_3/test.lst'
#test_list='/mnt/lustre/wanghao3/projects/PatCore/PatchCore_anomaly_detection/datapath/0908-0924/Cu_0/test_2.lst'
test_list='/mnt/lustre/wanghao3/projects/Knowlege_distillation_AD/Dataset/ciwa_data_list/3/test.lst'
#category='train_ds_2000'
category='resnet_merge_1000_no_trans'
num_epoch=1
batch_size=32
load_size=256
input_size=224
coreset_sampling_ratio=0.00025
project_root_path='/mnt/lustre/wanghao3/projects/PatCore/tmp'
save_src_code=True
save_anomaly_map=True
n_neighbors=9

srun -p mediaa --gres=gpu:1 \
        python ../train_wh.py \
        --phase=$phase \
        --dataset_path=$dataset_path \
        --category=$category \
        --num_epoch=$num_epoch \
        --batch_size=${batch_size} \
        --load_size=$load_size \
        --input_size=$input_size \
        --coreset_sampling_ratio=$coreset_sampling_ratio \
        --project_root_path=$project_root_path \
        --n_neighbors=$n_neighbors \
        --train_list=$train_list \
        --test_list=$test_list
